### ISSUE TITLE
Add a loding spinner on landing page

### ISSUE THREAD

**Issue by abhayofc** [mrigaankzoro/ScholarStation#25]
Show a loading spinner until the landing page loades

**Comment by SusanGithaigaN** [comment]
@abhayofc can I take this issue?

**Comment by SusanGithaigaN** [comment]
I'm getting the following error when I run npm install since there is no package.json file:
![image](https://github.com/user-attachments/assets/a048cd90-22d9-46c9-abf2-80aaf9ef499c)

**Comment by 2021eo3ar** [comment]
@mrigaankzoro could you please assign me this issue I can come up with a better solution.

**Comment by mrigaankzoro** [comment]
Its not possible to run this you have to install almost all react lib and
vite

**Comment by SusanGithaigaN** [comment]
None of that is installed on the project, and to use npm you have to have the packages installed.

Doesn't doing the initial installations make the process of making a contribution harder, package version errors and other factors considered?

**Comment by abhayofc** [comment]
> None of that is installed on the project, and to use npm you have to have the packages installed.
> 
> Doesn't doing the initial installations make the process of making a contribution harder, package version errors and other factors considered?

Bro, the code for frontend is in the Client folder and backend in in the API, you are trying to npm I in the root folder, have some common sense man

**Comment by mrigaankzoro** [comment]
Hn ... Ek dum shi the main project is in client folder

**Comment by mrigaankzoro** [comment]
this issue has been resolved by @MRIGAANKSh
