### ISSUE TITLE
Fix responsiveness of the navbar

### ISSUE THREAD

**Issue by abhayofc** [mrigaankzoro/ScholarStation#29]
fix this responsive issue of the navbar and open a pr

![image](https://github.com/user-attachments/assets/738ff505-aa87-4f41-8f3d-a67cade20292)

**Comment by Nipun1a** [comment]
Hi Mrigaank Sharma

I hope you're doing well.

I’m reaching out to request your assistance in enhancing the responsiveness of the navbar in our project. Currently, we’ve noticed some issues when viewed on different screen sizes, and it would be great to have it adjusted for a smoother, more adaptive user experience.

Your expertise would be highly valuable in resolving this, and I look forward to your thoughts and any suggestions you may have.

Thank you for your help!

Best regards,  
[Nipun]

**Comment by mrigaankzoro** [comment]
Done
