### ISSUE TITLE
Create a logo for the ScholarStation-Non Tech.

### ISSUE THREAD

**Issue by mrigaankzoro** [mrigaankzoro/ScholarStation#3]
Description: Design a creative and professional logo for the Scholar Station platform. The logo should reflect the platform's focus on academic resources, collaboration, and networking. Once completed, insert the image file into the assets/logos folder of the repository.

This task is open to non-technical contributors! 
make a public or assest folder and insert the logo in it .

**Comment by Prashant24005** [comment]
Assign me this issue

**Comment by mrigaankzoro** [comment]
Thansk for contribution

**Comment by Parth844** [comment]
Assign me this issue

**Comment by mrigaankzoro** [comment]
@Parth844 @Prashant24005 pls make the logo
