### ISSUE TITLE
Design-NonTech

### ISSUE THREAD

**Issue by mrigaankzoro** [mrigaankzoro/ScholarStation#6]
Issue: Design Website Layout for Scholar Station (Non-Tech)

Description: Create a visually appealing layout design for the Scholar Station platform. This should include wireframes or mockups for key pages (Home, Resources, Collaborate, Contact). Provide the designs in the form of images or design files, and upload them to a separate designs/layout folder in the repository.

Perfect for non-technical contributors!

**Comment by Sarveshk76** [comment]
Hi @mrigaankzoro , I would like to work on this issue

**Comment by mrigaankzoro** [comment]
Thankyou for your contribution

**Comment by mrigaankzoro** [comment]
Pls share the design if u have made we will start the work by today itself and marks as dat 1
