### ISSUE TITLE
styling the site.

### ISSUE THREAD

**Issue by mrigaankzoro** [mrigaankzoro/ScholarStation#8]
Style the site and btns ....

**Comment by bhatiatanish225** [comment]
The website is in html , css 

i will create a responsive a website in react with good ui/ux so pls assign me this issue.

**Comment by mrigaankzoro** [comment]
The site will be both in react version and basic for new bies .for react version I have created a serparte issue comment on it so I will assign i t to you

**Comment by uzefaqureshi06** [comment]
can you please please assign this issue to me i will make my best

**Comment by mrigaankzoro** [comment]
Done

**Comment by mrigaankzoro** [comment]
@uzefaqureshi06 done

**Comment by abhayofc** [comment]
![WhatsApp Image 2024-10-08 at 23 48 40_f58a7899](https://github.com/user-attachments/assets/e0c24bd2-ce0f-4b60-a94e-993a4c2049fc)

**Comment by mrigaankzoro** [comment]
Check Acegrade.in for further design we will keep minimilistic
